version: '3.8'
services:
  whatsapp: 
    image: aepnh14/kirimwa
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 90:80
    volumes:
      - ./data:/app/data
