version: '3.8'
services:
  whatsapp: 
    image: aepnh14/kirimwa:2.0.2
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - ./data:/app/data
