version: '3.9'
services:
  whatsapp: 
    image: taufikdev88/simplewhatsappapi:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - ./data:/app/data
